version: '3.2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
#    restart: always
  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://192.168.180.30:9092
      - KAFKA_LISTENERS=PLAINTEXT://:9092
      - KAFKA_MESSAGE_MAX_BYTES=5242880
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
#    restart: always
